In [3]:
df = pd.read_csv('/kaggle/input/price-of-used-toyota-corolla-cars/ToyotaCorolla.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Model              1436 non-null   object
 2   Price              1436 non-null   int64
 3   Age_08_04          1436 non-null   int64
 4   Mfg_Month          1436 non-null   int64
 5   Mfg_Year           1436 non-null   int64
 6   KM                 1436 non-null   int64
 7   Fuel_Type          1436 non-null   object
 8   HP                 1436 non-null   int64
 9   Met_Color          1436 non-null   int64
 10  Color              1436 non-null   object
 11  Automatic          1436 non-null   int64
 12  CC                 1436 non-null   int64
 13  Doors              1436 non-null   int64
 14  Cylinders          1436 non-null   int64
 15  Gears              1436 non-null   int64
 16  Quarterly_Tax      1436 non-null   int64
 17  Weight             1436 non-null   int64
 18  Mfr_Guarantee      1436 non-null   int64
 19  BOVAG_Guarantee    1436 non-null   int64
 20  Guarantee_Period   1436 non-null   int64
 21  ABS                1436 non-null   int64
 22  Airbag_1           1436 non-null   int64
 23  Airbag_2           1436 non-null   int64
 24  Airco              1436 non-null   int64
 25  Automatic_airco    1436 non-null   int64
 26  Boardcomputer      1436 non-null   int64
 27  CD_Player          1436 non-null   int64
 28  Central_Lock       1436 non-null   int64
 29  Powered_Windows    1436 non-null   int64
 30  Power_Steering     1436 non-null   int64
 31  Radio              1436 non-null   int64
 32  Mistlamps          1436 non-null   int64
 33  Sport_Model        1436 non-null   int64
 34  Backseat_Divider   1436 non-null   int64
 35  Metallic_Rim       1436 non-null   int64
 36  Radio_cassette     1436 non-null   int64
 37  Parking_Assistant  1436 non-null   int64
 38  Tow_Bar            1436 non-null   int64
dtypes: int64(36), object(3)
memory usage: 437.7+ KB

**Goal: Create a model to predict prices**

In [5]:
numerical = df.select_dtypes(exclude='object')

In [6]:
df.head()

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,1,0,0,0,1,0,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0

In [7]:
df.describe(include='all')

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.000000,1436,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436,1436.000000,1436.000000,...,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000
unique,NaN,319,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...,NaN,NaN,NaN,NaN,NaN,Petrol,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,109,NaN,NaN,NaN,NaN,NaN,1264,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,721.555014,NaN,10730.824513,55.947075,5.548747,1999.625348,68533.259749,NaN,101.502089,0.674791,...,0.561978,0.977716,0.146240,0.256964,0.300139,0.770195,0.204735,0.145543,0.002786,0.277855
std,416.476890,NaN,3626.964585,18.599988,3.354085,1.540722,37506.448872,NaN,14.981080,0.468616,...,0.496317,0.147657,0.353469,0.437111,0.458478,0.420854,0.403649,0.352770,0.052723,0.448098
min,1.000000,NaN,4350.000000,1.000000,1.000000,1998.000000,1.000000,NaN,69.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,361.750000,NaN,8450.000000,44.000000,3.000000,1998.000000,43000.000000,NaN,90.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,721.500000,NaN,9900.000000,61.000000,5.000000,1999.000000,63389.500000,NaN,110.000000,1.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1081.250000,NaN,11950.000000,70.000000,8.000000,2001.000000,87020.750000,NaN,110.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,1442.000000,NaN,32500.000000,80.000000,12.000000,2004.000000,243000.000000,NaN,192.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Model              1436 non-null   object
 2   Price              1436 non-null   int64
 3   Age_08_04          1436 non-null   int64
 4   Mfg_Month          1436 non-null   int64
 5   Mfg_Year           1436 non-null   int64
 6   KM                 1436 non-null   int64
 7   Fuel_Type          1436 non-null   object
 8   HP                 1436 non-null   int64
 9   Met_Color          1436 non-null   int64
 10  Color              1436 non-null   object
 11  Automatic          1436 non-null   int64
 12  CC                 1436 non-null   int64
 13  Doors              1436 non-null   int64
 14  Cylinders          1436 non-null   int64
 15  Gears              1436 non-null   int64
 16  Quarterly_Tax      1436 non-null   int64
 17  Weight             1436 non-null   int64
 18  Mfr_Guarantee      1436 non-null   int64
 19  BOVAG_Guarantee    1436 non-null   int64
 20  Guarantee_Period   1436 non-null   int64
 21  ABS                1436 non-null   int64
 22  Airbag_1           1436 non-null   int64
 23  Airbag_2           1436 non-null   int64
 24  Airco              1436 non-null   int64
 25  Automatic_airco    1436 non-null   int64
 26  Boardcomputer      1436 non-null   int64
 27  CD_Player          1436 non-null   int64
 28  Central_Lock       1436 non-null   int64
 29  Powered_Windows    1436 non-null   int64
 30  Power_Steering     1436 non-null   int64
 31  Radio              1436 non-null   int64
 32  Mistlamps          1436 non-null   int64
 33  Sport_Model        1436 non-null   int64
 34  Backseat_Divider   1436 non-null   int64
 35  Metallic_Rim       1436 non-null   int64
 36  Radio_cassette     1436 non-null   int64
 37  Parking_Assistant  1436 non-null   int64
 38  Tow_Bar            1436 non-null   int64
dtypes: int64(36), object(3)
memory usage: 437.7+ KB

In [9]:
df.columns = map(str.lower,df.columns)

In [10]:
df.groupby('automatic')['price'].mean().reset_index()

   automatic        price
0          0  10701.69174
1          1  11224.62500

There is a difference between the average price of automatic cars and manual cars. Further analysis would be done to check whether or not it is by chance.

In [11]:
from scipy.stats import f_oneway,ttest_ind

In [12]:
tstat,pval = ttest_ind(df.loc[df.automatic==0,'price'],df.loc[df.automatic==1,'price'])
#Null Hypothesis: There is no association between automatic cars and price
#Alternative Hypothesis: There is an association between automatic cars and price; Whether or not the car is automatic influences the price.
if pval <0.05:
    print('Reject Null Hypothesis. There is an association between price and automatic cars')
else:
    print('Accept Null Hypothesis. There is no association between price and automatic cars. Difference is by chance.')

Accept Null Hypothesis. There is no association between price and automatic cars. Difference is by chance.

In [13]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [14]:
features = []

Going to add features that influence the price of cars; whether or not the car is automatic has no influence so it wont be added.

In [15]:
df.fuel_type.value_counts()

fuel_type
Petrol    1264
Diesel     155
CNG         17
Name: count, dtype: int64

In [16]:
fstat,pval = f_oneway(df.loc[df.fuel_type=='Petrol','price'],df.loc[df.fuel_type=='Diesel','price'],df.loc[df.fuel_type=='CNG','price'])
#Null Hypothesis: There is no association between any of the fuel types and price.
#Alternative Hypothesis: There is an association between atleast two fuel types and price.
if pval <0.05:
    print('Reject Null Hypothesis. There is atleast an association between two fuel types.')
else:
    print('Accept Null Hypothesis. There is no association between any of the fuel types.')

Reject Null Hypothesis. There is atleast an association between two fuel types.

In [17]:
result = pairwise_tukeyhsd(df.price,df.fuel_type)
print(result)

   Multiple Comparison of Means - Tukey HSD, FWER=0.05
==========================================================
group1 group2  meandiff p-adj    lower      upper   reject
----------------------------------------------------------
   CNG Diesel 1873.3784 0.1067  -297.4822 4044.2389  False
   CNG Petrol 1258.1337 0.3294  -816.4673 3332.7346  False
Diesel Petrol -615.2447 0.1135 -1338.3638  107.8744  False
----------------------------------------------------------

There is an between all the fuel types; all three possible combinations.
Adding 'fuel_type' to the features.

In [18]:
features.append('fuel_type')

In [19]:
df.cd_player.value_counts()

cd_player
0    1122
1     314
Name: count, dtype: int64

In [20]:
tstat,pval = ttest_ind(df.loc[df.cd_player==0,'price'],df.loc[df.cd_player==1,'price'])
#Null Hypothesis: There is no association between cars with cd player and price
#Alternative Hypothesis: There is an association between cars with cd player and price; Whether or not the car has a cd player influences the price.
if pval <0.05:
    print('Reject Null Hypothesis. There is an association between cars with cd player and price')
else:
    print('Accept Null Hypothesis. There is no association between price and cd player. Difference is by chance.')

Reject Null Hypothesis. There is an association between cars with cd player and price

Adding cd player to features.

In [21]:
features.append('cd_player')

In [22]:
print('Min: ',df.weight.min())
print('Max: ',df.weight.max())

Min:  1000
Max:  1615

Going to divide weight into two categories; 1000-1300 and 1300-1615.

In [23]:
weight_a = df.query('1000<=weight<=1300')
weight_b = df.query('1300<=weight<=1615')

In [24]:
tstat,pval = ttest_ind(weight_a.price,weight_b.price)
if pval <0.05:
    print('Reject Null Hypothesis. There is an association between weight and price.')
else:
    print('Accept Null Hypothesis. There is no association between weight and price. Difference is by chance.')

Reject Null Hypothesis. There is an association between weight and price.

In [25]:
features.append('weight')

In [26]:
df.boardcomputer.value_counts()

boardcomputer
0    1013
1     423
Name: count, dtype: int64

In [27]:
tstat,pval = ttest_ind(df.loc[df.boardcomputer==0,'price'],df.loc[df.boardcomputer==1,'price'])
if pval <0.05:
    print('Reject Null Hypothesis. There is an association between cars with board computer and price.')
else:
    print('Accept Null Hypothesis. There is no association between cars with board computer and price. Difference is by chance.')

Reject Null Hypothesis. There is an association between cars with board computer and price.

In [28]:
features.append('boardcomputer')

In [29]:
df.airco.value_counts()

airco
1    730
0    706
Name: count, dtype: int64

In [30]:
tstat,pval = ttest_ind(df.loc[df.airco==0,'price'],df.loc[df.airco==1,'price'])
if pval <0.05:
    print('Reject Null Hypothesis. There is an association between cars with air conditioner and price.')
else:
    print('Accept Null Hypothesis. There is no association between cars with air conditioner and price. Difference is by chance.')

Reject Null Hypothesis. There is an association between cars with air conditioner and price.

In [31]:
features.append('airco')

In [32]:
df.automatic_airco.value_counts()

automatic_airco
0    1355
1      81
Name: count, dtype: int64

In [33]:
tstat,pval = ttest_ind(df.loc[df.automatic_airco==0,'price'],df.loc[df.automatic_airco==1,'price'])
if pval <0.05:
    print('Reject Null Hypothesis. There is an association between cars with automatic air conditioner and price.')
else:
    print('Accept Null Hypothesis. There is no association between cars with automatic air conditioner and price. Difference is by chance.')

Reject Null Hypothesis. There is an association between cars with automatic air conditioner and price.

In [34]:
features.append('automatic_airco')

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split

In [36]:
df[features].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fuel_type        1436 non-null   object
 1   cd_player        1436 non-null   int64
 2   weight           1436 non-null   int64
 3   boardcomputer    1436 non-null   int64
 4   airco            1436 non-null   int64
 5   automatic_airco  1436 non-null   int64
dtypes: int64(5), object(1)
memory usage: 67.4+ KB

In [37]:
df = pd.get_dummies(data=df,columns=['fuel_type'])

In [38]:
df.head()

,id,model,price,age_08_04,mfg_month,mfg_year,km,hp,met_color,color,...,mistlamps,sport_model,backseat_divider,metallic_rim,radio_cassette,parking_assistant,tow_bar,fuel_type_CNG,fuel_type_Diesel,fuel_type_Petrol
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,90,1,Blue,...,0,0,1,0,0,0,0,False,True,False
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,90,1,Silver,...,0,0,1,0,0,0,0,False,True,False
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,90,1,Blue,...,0,0,1,0,0,0,0,False,True,False
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,90,0,Black,...,0,0,1,0,0,0,0,False,True,False
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,90,0,Black,...,1,0,1,0,0,0,0,False,True,False

In [39]:
features.remove('fuel_type')
X = df[features+['fuel_type_CNG','fuel_type_Diesel','fuel_type_Petrol']]
y = df.price

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.25,random_state=40)
model1 = LinearRegression()
model1.fit(X_train,y_train)

LinearRegression()

In [40]:
ypred = model1.predict(X_test)
r2_score(y_test,ypred)

0.7377605916569091

The model can account for 73% of the variation in prices; it is 73% accurate.

In [41]:
np.where(numerical.corr()>0.4,)

(array([ 0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  3,  4,  4,  4,  4,
         4,  4,  4,  5,  5,  6,  7,  8,  9, 10, 12, 13, 13, 14, 14, 14, 14,
        14, 15, 16, 16, 17, 18, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 21,
        21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25,
        26, 26, 26, 26, 27, 27, 28, 28, 29, 29, 29, 29, 29, 30, 31, 31, 31,
        32, 32, 33, 33, 34, 35]),
 array([ 0,  2,  1,  4, 14, 21, 22, 23, 24,  0,  2,  5,  3,  1,  4, 14, 18,
        22, 23, 24,  2,  5,  6,  7,  8,  9, 10, 12, 13, 14,  1,  4, 13, 14,
        22, 15, 16, 31, 17,  4, 18, 20, 19, 27, 18, 20, 31,  1, 21, 25, 26,
        29,  1,  4, 14, 22,  1,  4, 23, 24,  1,  4, 23, 24, 21, 25, 26, 29,
        21, 25, 26, 29, 19, 27, 28, 33, 21, 25, 26, 29, 32, 30, 16, 20, 31,
        29, 32, 28, 33, 34, 35]))

In [42]:
numerical.corr().iloc[np.where(numerical.corr()>0.4)]

,Id,Age_08_04,Price,Mfg_Year,Weight,Airco,Automatic_airco,Boardcomputer,CD_Player,Id,...,Sport_Model,BOVAG_Guarantee,Airbag_2,Backseat_Divider,Mistlamps,Metallic_Rim,Radio,Radio_cassette,Parking_Assistant,Tow_Bar
Id,1.000000,0.906132,-0.738250,-0.919523,-0.414500,-0.386207,-0.327468,-0.695207,-0.464520,1.000000,...,-0.028704,-0.015065,-0.358316,-0.136398,-0.139708,-0.022232,-0.010971,-0.011611,-0.049103,0.159171
Id,1.000000,0.906132,-0.738250,-0.919523,-0.414500,-0.386207,-0.327468,-0.695207,-0.464520,1.000000,...,-0.028704,-0.015065,-0.358316,-0.136398,-0.139708,-0.022232,-0.010971,-0.011611,-0.049103,0.159171
Price,-0.738250,-0.876590,1.000000,0.885159,0.581198,0.429259,0.588262,0.601292,0.481374,-0.738250,...,0.164121,0.028133,0.248974,0.102569,0.222083,0.108564,-0.041887,-0.043179,0.044375,-0.172369
Price,-0.738250,-0.876590,1.000000,0.885159,0.581198,0.429259,0.588262,0.601292,0.481374,-0.738250,...,0.164121,0.028133,0.248974,0.102569,0.222083,0.108564,-0.041887,-0.043179,0.044375,-0.172369
Price,-0.738250,-0.876590,1.000000,0.885159,0.581198,0.429259,0.588262,0.601292,0.481374,-0.738250,...,0.164121,0.028133,0.248974,0.102569,0.222083,0.108564,-0.041887,-0.043179,0.044375,-0.172369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Metallic_Rim,-0.022232,-0.040045,0.108564,0.036022,0.053847,0.233166,0.100363,-0.024999,0.044730,-0.022232,...,0.051810,0.060434,0.075128,0.104862,0.412545,1.000000,-0.034162,-0.033228,-0.026816,-0.037331
Radio_cassette,-0.011611,0.012857,-0.043179,-0.018844,-0.037265,-0.036524,-0.092348,-0.128073,-0.189668,-0.011611,...,-0.136708,-0.039827,-0.220917,-0.206390,-0.134245,-0.033228,0.991621,1.000000,0.015655,0.140753
Radio_cassette,-0.011611,0.012857,-0.043179,-0.018844,-0.037265,-0.036524,-0.092348,-0.128073,-0.189668,-0.011611,...,-0.136708,-0.039827,-0.220917,-0.206390,-0.134245,-0.033228,0.991621,1.000000,0.015655,0.140753
Parking_Assistant,-0.049103,-0.048172,0.044375,0.047171,0.027660,0.051976,0.044350,0.052803,0.035973,-0.049103,...,-0.005782,0.018050,0.003207,-0.002537,-0.000842,-0.026816,0.015520,0.015655,1.000000,0.026210
Tow_Bar,0.159171,0.188720,-0.172369,-0.182206,-0.074932,-0.024362,-0.117967,-0.128001,-0.079911,0.159171,...,-0.094147,-0.006718,-0.063956,-0.049176,-0.069479,-0.037331,0.143652,0.140753,0.026210,1.000000

In [43]:
len(numerical.columns)

36

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1436 non-null   int64
 1   model              1436 non-null   object
 2   price              1436 non-null   int64
 3   age_08_04          1436 non-null   int64
 4   mfg_month          1436 non-null   int64
 5   mfg_year           1436 non-null   int64
 6   km                 1436 non-null   int64
 7   hp                 1436 non-null   int64
 8   met_color          1436 non-null   int64
 9   color              1436 non-null   object
 10  automatic          1436 non-null   int64
 11  cc                 1436 non-null   int64
 12  doors              1436 non-null   int64
 13  cylinders          1436 non-null   int64
 14  gears              1436 non-null   int64
 15  quarterly_tax      1436 non-null   int64
 16  weight             1436 non-null   int64
 17  mfr_guarantee      1436 non-null   int64
 18  bovag_guarantee    1436 non-null   int64
 19  guarantee_period   1436 non-null   int64
 20  abs                1436 non-null   int64
 21  airbag_1           1436 non-null   int64
 22  airbag_2           1436 non-null   int64
 23  airco              1436 non-null   int64
 24  automatic_airco    1436 non-null   int64
 25  boardcomputer      1436 non-null   int64
 26  cd_player          1436 non-null   int64
 27  central_lock       1436 non-null   int64
 28  powered_windows    1436 non-null   int64
 29  power_steering     1436 non-null   int64
 30  radio              1436 non-null   int64
 31  mistlamps          1436 non-null   int64
 32  sport_model        1436 non-null   int64
 33  backseat_divider   1436 non-null   int64
 34  metallic_rim       1436 non-null   int64
 35  radio_cassette     1436 non-null   int64
 36  parking_assistant  1436 non-null   int64
 37  tow_bar            1436 non-null   int64
 38  fuel_type_CNG      1436 non-null   bool
 39  fuel_type_Diesel   1436 non-null   bool
 40  fuel_type_Petrol   1436 non-null   bool
dtypes: bool(3), int64(36), object(2)
memory usage: 430.6+ KB

In [46]:
import statsmodels.api as sm
model2 = sm.OLS.from_formula('price~weight+km+model+backseat_divider+metallic_rim',df).fit()
model2.rsquared_adj

0.9136351943392509

Model 2 is 91% accurate.